# Data Validation

## What is Data Validation?
### Step 1 – Understand the Concept (Markdown)
Definition: Data Validation is the process of checking whether data is correct, valid, and follows predefined rules.

In simple words: Data Validation = Checking whether data is correct and acceptable.

### Step 2 – Demonstrate the Concept (Markdown)
Simple example:
    
Age → 25       ✅ Valid
Age → -5       ❌ Invalid
Email → a@gmail.com  ✅ Valid
Email → abc    ❌ Invalid

### Step 3 – Implement the Concept (Python)

In [26]:
import pandas as pd

data = {
    "Name" : ["mahi", "raju"],
    "age"  : [20,10],
    "salary": [20000,-50000],
    "gender" : ["Male", "Female"]
}
df = pd.DataFrame(data)

df

   Name  age  salary  gender
0  mahi   20   20000    Male
1  raju   10  -50000  Female

In [27]:
#df = df[df["age"] >= 18]

df

   Name  age  salary  gender
0  mahi   20   20000    Male
1  raju   10  -50000  Female

## Range Validation
### Step 1 – Understand the Concept (Markdown)
Definition: Range Validation checks whether a value falls within a specified minimum and maximum range.

In simple words:Range Validation = Check whether a value is within the allowed range.

### Step 2 – Demonstrate the Concept (Markdown)
Simple example:
Age = 25   ✅ Valid (0–100)
Age = 150  ❌ Invalid
Age = -5   ❌ Invalid

### Step 3 – Implement the Concept (Python)

In [32]:
# Keep Age between 0 and 100

df = df[(df["age"] >= 18 ) & (df["age"] <= 100)]
df

   Name  age  salary gender
0  mahi   20   20000   Male

## Type Validation
### Step 1 – Understand the Concept (Markdown)
Definition: Type Validation checks whether a value has the correct data type as expected.

In simple words: Type Validation = Check whether data is in the correct type.

### Step 2 – Demonstrate the Concept (Markdown)
Simple example:
Age = 25       ✅ Integer
Age = "25"     ❌ String
Salary = 30000 ✅ Numeric

### Step 3 – Implement the Concept (Python)

In [34]:
# Check data types
print(df.dtypes)

# Check if Age is numeric
print(pd.api.types.is_numeric_dtype(df["age"]))

Name      object
age        int64
salary     int64
gender    object
dtype: object
True

In [ ]:
## Format Validation
### Step 1 – Understand the Concept (Markdown)
Definition: Format Validation checks whether data follows a required format or pattern.

In simple words: Format Validation = Check whether data follows the correct format.

### Step 2 – Demonstrate the Concept (Markdown)
Simple example:
Email → mani@gmail.com    ✅ Valid
Email → mani@             ❌ Invalid


Phone → 9876543210        ✅ Valid
Phone → 12345             ❌ Invalid

### Step 3 – Implement the Concept (Python)

# Check email format
df["Valid_Email"] = df["Email"].str.match(
    r"^[\w\.-]+@[\w\.-]+\.\w+$"
)

print(df)

## Category Validation
### Step 1 – Understand the Concept (Markdown)
Definition: Category Validation checks whether values belong to a predefined list of allowed categories.

In simple words: Category Validation = Check whether the value is an allowed category.

### Step 2 – Demonstrate the Concept (Markdown)
Simple example:

Allowed categories:

IT, HR, Sales
IT       ✅ Valid
HR       ✅ Valid
Finance  ❌ Invalid

### Step 3 – Implement the Concept (Python)

In [ ]:
allowed = ["IT", "HR", "Sales"]

df["Valid"] = df["Department"].isin(allowed)

print(df)

## Null Validation
### Step 1 – Understand the Concept (Markdown)
Definition:Null Validation checks whether required fields contain missing or null values.

In simple words: Null Validation = Check whether required data is present.

### Step 2 – Demonstrate the Concept (Markdown)
Simple example:

Name   → "Mani"   ✅ Valid
Age    → 25       ✅ Valid
Email  → NaN      ❌ Invalid

### Step 3 – Implement the Concept (Python)

In [36]:
# Check null values
print(df.isnull().sum())

# Check if Age has no null values
print(df["age"].notnull())

Name      0
age       0
salary    0
gender    0
dtype: int64
0    True
Name: age, dtype: bool

In [ ]:
## Business Rule Validation
### Step 1 – Understand the Concept (Markdown)
Definition: Business Rule Validation checks whether data follows the specific rules defined by the business.

In simple words: Business Rule Validation = Check whether data follows business requirements.

### Step 2 – Demonstrate the Concept (Markdown)
Simple example:

Business rule:

Age must be 18 or above.
Salary must be greater than 0.
Age = 25      ✅ Valid
Age = 15      ❌ Invalid
Salary = 30000 ✅ Valid
Salary = -500  ❌ Invalid

### Step 3 – Implement the Concept (Python)

In [37]:
# Business rule: Age must be >= 18
df["Valid_Age"] = df["age"] >= 18

# Business rule: Salary must be > 0
df["Valid_Salary"] = df["salary"] > 0

print(df)

   Name  age  salary gender  Valid_Age  Valid_Salary
0  mahi   20   20000   Male       True          True

C:\Users\new\AppData\Local\Temp\ipykernel_6768\2483429268.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Valid_Age"] = df["age"] >= 18
C:\Users\new\AppData\Local\Temp\ipykernel_6768\2483429268.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Valid_Salary"] = df["salary"] > 0

In [ ]:
## Referential Validation
### Step 1 – Understand the Concept (Markdown)
Definition: Referential Validation checks whether values in one table correctly match related values in another table.

In simple words: Referential Validation = Check whether a reference exists in the related table.

### Step 2 – Demonstrate the Concept (Markdown)
Simple example:

Customers

Customer_ID
101
102

Orders

Customer_ID
101 ✅
103 ❌

### Step 3 – Implement the Concept (Python)
# Find invalid Customer_IDs
invalid = orders[
    ~orders["Customer_ID"].isin(customers["Customer_ID"])
]

print(invalid)

## Date Validation
### Step 1 – Understand the Concept (Markdown)
Definition:Date Validation checks whether dates are valid, correctly formatted, and within an acceptable range.

In simple words: Date Validation = Check whether a date is correct and acceptable.

### Step 2 – Demonstrate the Concept (Markdown)
Simple example:
2026-08-20  → ✅ Valid
2026-13-40  → ❌ Invalid

### Step 3 – Implement the Concept (Python)
import pandas as pd

df["Joining_Date"] = pd.to_datetime(
    df["Joining_Date"],
    errors="coerce"
)

 Check valid dates
print(df["Joining_Date"].notnull())

## Constraint Validation
### Step 1 – Understand the Concept (Markdown)
Definition:Constraint Validation checks whether data follows predefined restrictions or conditions.

In simple words: Constraint Validation = Check whether data follows required rules or limits.

### Step 2 – Demonstrate the Concept (Markdown)
Age must be ≥ 18
Salary must be > 0
Email must not be empty

### Step 3 – Implement the Concept (Python)

In [39]:
# Check constraints
df["Valid"] = (
    (df["age"] >= 18) &
    (df["salary"] > 0)
)

print(df)

   Name  age  salary gender  Valid_Age  Valid_Salary  Valid
0  mahi   20   20000   Male       True          True   True

C:\Users\new\AppData\Local\Temp\ipykernel_6768\1925894648.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Valid"] = (

In [ ]:
| Type                         | What it checks          | Example              |
| ---------------------------- | ----------------------- | -------------------- |
| **Range Validation**         | Value is within a range | Age 0–100            |
| **Type Validation**          | Correct data type       | Age = Integer        |
| **Format Validation**        | Correct pattern         | Email format         |
| **Category Validation**      | Allowed categories      | IT, HR, Sales        |
| **Null Validation**          | Missing values          | Required field ≠ NaN |
| **Business Rule Validation** | Business requirements   | Age ≥ 18             |
| **Referential Validation**   | Related value exists    | Customer ID exists   |
| **Date Validation**          | Valid date              | Correct date & range |
| **Constraint Validation**    | Predefined restrictions | Salary > 0           |